# Generated by Django 5.0 on 2024-03-22 15:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="choice",
            name="choice_true_false",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="choice",
            name="choice_text",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
