# Generated by Django 5.0 on 2024-03-22 15:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0002_choice_choice_true_false_alter_choice_choice_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="question_type",
            field=models.CharField(
                choices=[("MCQ", "MCQ"), ("True/False", "True/False")],
                default="MCQ",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="choice",
            name="choice_true_false",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
