import 'package:vhack_finwise_app/model/podcast.dart';

import 'podcast_episode.dart';

class PodcastDatabase {
  static List<Podcast> podcastList = [
    Podcast(
      title: 'The Real Money show',
      host: 'Money TV',
      releaseDate: DateTime(2024, 2, 1),
      imagePath: 'assets/podcast/mrmoney/mrmoney.png',
      episodes: [
        Episode(
          title: 'EP1 - What is money?',
          durationInMinutes: '22',
          releaseDate: DateTime(2024, 1, 1),
          audioPath: 'assets/podcast/sample.mp3',
          imagePath: 'assets/podcast/mrmoney/mrmoney_ep.jpg',
          host: 'Money TV',
        ),
        Episode(
          title: 'EP2 - The truth about study debts',
          durationInMinutes: '40',
          releaseDate: DateTime(2024, 1, 7),
          audioPath: 'assets/podcast/sample.mp3',
          imagePath: 'assets/podcast/mrmoney/mrmoney_ep.jpg',
          host: 'Money TV',
        ),
        Episode(
          title: 'EP3 - What is stocks',
          durationInMinutes: '28',
          releaseDate: DateTime(2024, 1, 13),
          audioPath: 'assets/podcast/sample.mp3',
          imagePath: 'assets/podcast/mrmoney/mrmoney_ep.jpg',
          host: 'Money TV',
        ),
        Episode(
          title: 'EP4 - Genz...YOLO???',
          durationInMinutes: '90',
          releaseDate: DateTime(2024, 1, 19),
          audioPath: 'assets/podcast/sample.mp3',
          imagePath: 'assets/podcast/mrmoney/mrmoney_ep.jpg',
          host: 'Money TV',
        ),
        Episode(
          title: 'EP5 - Why FOMO is bad for your wallet',
          durationInMinutes: '34',
          releaseDate: DateTime(2024, 1, 25),
          audioPath: 'assets/podcast/sample.mp3',
          imagePath: 'assets/podcast/mrmoney/mrmoney_ep.jpg',
          host: 'Money TV',
        ),
      ],
    ),
    Podcast(
      title: 'The IHERNG Podcast',
      host: 'IHERNG',
      releaseDate: DateTime(2024, 2, 1),
      imagePath: 'assets/podcast/iherng/iherng.jpg',
      episodes: [
        Episode(
          title: 'EP1 - AIYA! Houses too expensive lah',
          durationInMinutes: '22',
          releaseDate: DateTime(2024, 2, 1),
          audioPath: 'assets/podcast/sample.mp3',
          imagePath: 'assets/podcast/iherng/iherng_ep.jpg',
          host: 'IHERNG',
        ),
        Episode(
          title: 'EP2 - The truth about how the rich play the property game',
          durationInMinutes: '40',
          releaseDate: DateTime(2024, 2, 7),
          audioPath: 'assets/podcast/sample.mp3',
          imagePath: 'assets/podcast/iherng/iherng_ep.jpg',
          host: 'IHERNG',
        ),
        Episode(
          title: 'EP3 - Equity game instead of money flipping game',
          durationInMinutes: '28',
          releaseDate: DateTime(2024, 2, 13),
          audioPath: 'assets/podcast/sample.mp3',
          imagePath: 'assets/podcast/iherng/iherng_ep.jpg',
          host: 'IHERNG',
        ),
        Episode(
          title: 'EP4 - Invest first or save first?',
          durationInMinutes: '90',
          releaseDate: DateTime(2024, 2, 19),
          audioPath: 'assets/podcast/sample.mp3',
          imagePath: 'assets/podcast/iherng/iherng_ep.jpg',
          host: 'IHERNG',
        ),
        Episode(
          title: 'EP5 - Is RumahWip the best investment?',
          durationInMinutes: '34',
          releaseDate: DateTime(2024, 2, 25),
          audioPath: 'assets/podcast/sample.mp3',
          imagePath: 'assets/podcast/iherng/iherng_ep.jpg',
          host: 'IHERNG',
        ),
      ],
    ),
    Podcast(
      title: 'Financial Faiz',
      host: 'Faiz',
      releaseDate: DateTime(2024, 2, 1),
      imagePath: 'assets/podcast/financial faiz/financialfiaz.jpeg',
      episodes: [
        Episode(
          title: 'EP1 - Mutual stock? is it safe? ',
          durationInMinutes: '22',
          releaseDate: DateTime(2024, 3, 1),
          audioPath: 'assets/podcast/sample.mp3',
          imagePath: 'assets/podcast/financial faiz/financialfaiz_ep.jpg',
          host: 'Faiz',
        ),
        Episode(
          title: 'EP2 - Why parents are bad financial advisors',
          durationInMinutes: '40',
          releaseDate: DateTime(2024, 3, 7),
          audioPath: 'assets/podcast/sample.mp3',
          imagePath: 'assets/podcast/financial faiz/financialfaiz_ep.jpg',
          host: 'Faiz',
        ),
        Episode(
          title: 'EP3 - How to handle Inflations',
          durationInMinutes: '28',
          releaseDate: DateTime(2024, 3, 13),
          audioPath: 'assets/podcast/sample.mp3',
          imagePath: 'assets/podcast/financial faiz/financialfaiz_ep.jpg',
          host: 'Faiz',
        ),
        Episode(
          title: 'EP4 - Make your first investment move',
          durationInMinutes: '90',
          releaseDate: DateTime(2024, 3, 19),
          audioPath: 'assets/podcast/sample.mp3',
          imagePath: 'assets/podcast/financial faiz/financialfaiz_ep.jpg',
          host: 'Faiz',
        ),
        Episode(
          title: 'EP5 - High risk high reward? is it true?',
          durationInMinutes: '34',
          releaseDate: DateTime(2024, 3, 25),
          audioPath: 'assets/podcast/sample.mp3',
          imagePath: 'assets/podcast/financial faiz/financialfaiz_ep.jpg',
          host: 'Faiz',
        ),
      ],
    ),
    Podcast(
      title: 'Change Your Perspective',
      host: 'Cheryl Lee',
      releaseDate: DateTime(2024, 2, 1),
      imagePath: 'assets/podcast/changemind/changemind.jpeg',
      episodes: [
        Episode(
          title: 'EP1 - Work life balance? Is it possible?',
          durationInMinutes: '22',
          releaseDate: DateTime(2024, 5, 1),
          audioPath: 'assets/podcast/sample.mp3',
          imagePath: 'assets/podcast/changemind/changemind_ep.jpg',
          host: 'Cheryl Lee',
        ),
        Episode(
          title: 'EP2 - The Side Gig era',
          durationInMinutes: '40',
          releaseDate: DateTime(2024, 5, 7),
          audioPath: 'assets/podcast/sample.mp3',
          imagePath: 'assets/podcast/changemind/changemind_ep.jpg',
          host: 'Cheryl Lee',
        ),
        Episode(
          title: 'EP3 - I hate financial stress, but...',
          durationInMinutes: '28',
          releaseDate: DateTime(2024, 5, 13),
          audioPath: 'assets/podcast/sample.mp3',
          imagePath: 'assets/podcast/changemind/changemind_ep.jpg',
          host: 'Cheryl Lee',
        ),
        Episode(
          title: 'EP4 - Handling financial as a Dad/Mom',
          durationInMinutes: '90',
          releaseDate: DateTime(2024, 5, 19),
          audioPath: 'assets/podcast/sample.mp3',
          imagePath: 'assets/podcast/changemind/changemind_ep.jpg',
          host: 'Cheryl Lee',
        ),
        Episode(
          title: 'EP5 - Starting life as a fresh grad',
          durationInMinutes: '34',
          releaseDate: DateTime(2024, 5, 25),
          audioPath: 'assets/podcast/sample.mp3',
          imagePath: 'assets/podcast/changemind/changemind_ep.jpg',
          host: 'Cheryl Lee',
        ),
      ],
    ),
  ];

  static List<Episode> trendingNow = [
    Episode(
      title: 'EP1 - Mutual stock? is it safe? ',
      durationInMinutes: '22',
      releaseDate: DateTime(2024, 3, 1),
      audioPath: 'assets/podcast/sample.mp3',
      imagePath: 'assets/podcast/financial faiz/financialfaiz_ep.jpg',
      host: 'Faiz',
    ),
    Episode(
        title: 'EP5 - Starting life as a fresh grad',
        durationInMinutes: '34',
        releaseDate: DateTime(2024, 5, 25),
        audioPath: 'assets/podcast/sample.mp3',
        imagePath: 'assets/podcast/changemind/changemind_ep.jpg',
        host: 'Cheryl'),
    Episode(
        title: 'EP4 - Genz...YOLO???',
        durationInMinutes: '90',
        releaseDate: DateTime(2024, 1, 19),
        audioPath: 'assets/podcast/sample.mp3',
        imagePath: 'assets/podcast/mrmoney/mrmoney_ep.jpg',
        host: 'Mr Money'),
    Episode(
      title: 'EP1 - AIYA! Houses too expensive lah',
      durationInMinutes: '22',
      releaseDate: DateTime(2024, 2, 1),
      audioPath: 'assets/podcast/sample.mp3',
      imagePath: 'assets/podcast/iherng/iherng_ep.jpg',
      host: 'IHERNG',
    ),
  ];

  static List<Episode> recentList = [
    Episode(
      title: 'EP1 - AIYA! Houses too expensive lah',
      durationInMinutes: '22',
      releaseDate: DateTime(2024, 2, 1),
      audioPath: 'assets/podcast/sample.mp3',
      imagePath: 'assets/podcast/iherng/iherng_ep.jpg',
      host: 'IHERNG',
    ),
    Episode(
        title: 'EP4 - Genz...YOLO???',
        durationInMinutes: '90',
        releaseDate: DateTime(2024, 1, 19),
        audioPath: 'assets/podcast/sample.mp3',
        imagePath: 'assets/podcast/mrmoney/mrmoney_ep.jpg',
        host: 'Mr Money'),
    Episode(
      title: 'EP1 - AIYA! Houses too expensive lah',
      durationInMinutes: '22',
      releaseDate: DateTime(2024, 2, 1),
      audioPath: 'assets/podcast/sample.mp3',
      imagePath: 'assets/podcast/iherng/iherng_ep.jpg',
      host: 'IHERNG',
    ),
  ];

  static List<Episode> youMightLikeList = [
    Episode(
      title: 'EP2 - Why parents are bad financial advisors',
      durationInMinutes: '40',
      releaseDate: DateTime(2024, 3, 7),
      audioPath: 'assets/podcast/sample.mp3',
      imagePath: 'assets/podcast/financial faiz/financialfaiz_ep.jpg',
      host: 'Faiz',
    ),
    Episode(
      title: 'EP3 - How to handle Inflations',
      durationInMinutes: '28',
      releaseDate: DateTime(2024, 3, 13),
      audioPath: 'assets/podcast/sample.mp3',
      imagePath: 'assets/podcast/financial faiz/financialfaiz_ep.jpg',
      host: 'Faiz',
    ),
    Episode(
      title: 'EP4 - Make your first investment move',
      durationInMinutes: '90',
      releaseDate: DateTime(2024, 3, 19),
      audioPath: 'assets/podcast/sample.mp3',
      imagePath: 'assets/podcast/financial faiz/financialfaiz_ep.jpg',
      host: 'Faiz',
    ),
    Episode(
      title: 'EP5 - High risk high reward? is it true?',
      durationInMinutes: '34',
      releaseDate: DateTime(2024, 3, 25),
      audioPath: 'assets/podcast/sample.mp3',
      imagePath: 'assets/podcast/financial faiz/financialfaiz_ep.jpg',
      host: 'Faiz',
    ),
  ];

  static List<Podcast> likedPodcastList = [
    Podcast(
      title: 'The IHERNG Podcast',
      host: 'IHERNG',
      releaseDate: DateTime(2024, 2, 1),
      imagePath: 'assets/podcast/iherng/iherng.jpg',
      episodes: [
        Episode(
          title: 'EP1 - AIYA! Houses too expensive lah',
          durationInMinutes: '22',
          releaseDate: DateTime(2024, 2, 1),
          audioPath: 'assets/podcast/sample.mp3',
          imagePath: 'assets/podcast/iherng/iherng_ep.jpg',
          host: 'IHERNG',
        ),
        Episode(
          title: 'EP2 - The truth about how the rich play the property game',
          durationInMinutes: '40',
          releaseDate: DateTime(2024, 2, 7),
          audioPath: 'assets/podcast/sample.mp3',
          imagePath: 'assets/podcast/iherng/iherng_ep.jpg',
          host: 'IHERNG',
        ),
        Episode(
          title: 'EP3 - Equity game instead of money flipping game',
          durationInMinutes: '28',
          releaseDate: DateTime(2024, 2, 13),
          audioPath: 'assets/podcast/sample.mp3',
          imagePath: 'assets/podcast/iherng/iherng_ep.jpg',
          host: 'IHERNG',
        ),
        Episode(
          title: 'EP4 - Invest first or save first?',
          durationInMinutes: '90',
          releaseDate: DateTime(2024, 2, 19),
          audioPath: 'assets/podcast/sample.mp3',
          imagePath: 'assets/podcast/iherng/iherng_ep.jpg',
          host: 'IHERNG',
        ),
        Episode(
          title: 'EP5 - Is RumahWip the best investment?',
          durationInMinutes: '34',
          releaseDate: DateTime(2024, 2, 25),
          audioPath: 'assets/podcast/sample.mp3',
          imagePath: 'assets/podcast/iherng/iherng_ep.jpg',
          host: 'IHERNG',
        ),
      ],
    ),
    Podcast(
      title: 'The Real Money show',
      host: 'Money TV',
      releaseDate: DateTime(2024, 2, 1),
      imagePath: 'assets/podcast/mrmoney/mrmoney.png',
      episodes: [
        Episode(
          title: 'EP1 - What is money?',
          durationInMinutes: '22',
          releaseDate: DateTime(2024, 1, 1),
          audioPath: 'assets/podcast/sample.mp3',
          imagePath: 'assets/podcast/mrmoney/mrmoney_ep.jpg',
          host: 'Money TV',
        ),
        Episode(
          title: 'EP2 - The truth about study debts',
          durationInMinutes: '40',
          releaseDate: DateTime(2024, 1, 7),
          audioPath: 'assets/podcast/sample.mp3',
          imagePath: 'assets/podcast/mrmoney/mrmoney_ep.jpg',
          host: 'Money TV',
        ),
        Episode(
          title: 'EP3 - What is stocks',
          durationInMinutes: '28',
          releaseDate: DateTime(2024, 1, 13),
          audioPath: 'assets/podcast/sample.mp3',
          imagePath: 'assets/podcast/mrmoney/mrmoney_ep.jpg',
          host: 'Money TV',
        ),
        Episode(
          title: 'EP4 - Genz...YOLO???',
          durationInMinutes: '90',
          releaseDate: DateTime(2024, 1, 19),
          audioPath: 'assets/podcast/sample.mp3',
          imagePath: 'assets/podcast/mrmoney/mrmoney_ep.jpg',
          host: 'Money TV',
        ),
        Episode(
          title: 'EP5 - Why FOMO is bad for your wallet',
          durationInMinutes: '34',
          releaseDate: DateTime(2024, 1, 25),
          audioPath: 'assets/podcast/sample.mp3',
          imagePath: 'assets/podcast/mrmoney/mrmoney_ep.jpg',
          host: 'Money TV',
        ),
      ],
    ),
  ];
}
