# Generated by Django 5.0 on 2024-03-21 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("podcast", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="podcast",
            name="session_date",
        ),
        migrations.RemoveField(
            model_name="podcast",
            name="session_time",
        ),
        migrations.AddField(
            model_name="podcast",
            name="podcast_slug",
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.CreateModel(
            name="Episode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("audio_file", models.FileField(upload_to="audio_files/")),
                ("release_date", models.DateTimeField(auto_now_add=True)),
                ("duration_in_minutes", models.FloatField(blank=True, null=True)),
                (
                    "podcast",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="episodes",
                        to="podcast.podcast",
                    ),
                ),
            ],
        ),
    ]
