# Generated by Django 5.0 on 2024-03-10 08:34

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='InfoType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('News', 'News'), ('Quizes', 'Quizes')], max_length=10)),
            ],
        ),
        migrations.AddConstraint(
            model_name='domain',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Upper('name'), name='unique_domain_upper_name'),
        ),
        migrations.AddField(
            model_name='infotype',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.domain'),
        ),
    ]
