# Generated by Django 5.0 on 2024-03-10 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(default=None, upload_to='news_images/'),
        ),
    ]
